<?php

namespace GPI\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{

}
