gpi_site:
    resource: "@GPISiteBundle/Resources/config/routing.yml"
    prefix:   /

gpi_document:
    resource: "@GPIDocumentBundle/Resources/config/routing.yml"
    prefix:   /

gpi_offer:
    resource: "@GPIOfferBundle/Resources/config/routing.yml"
    prefix:   /

gpi_auction:
    resource: "@GPIAuctionBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
#
# Support for LiipImagineBundle
#_imagine:
#    resource: .
#    type:     imagine

_front:
    resource: routing_front.yml

_admin:
    resource: routing_admin.yml
    prefix:   /admin

_api:
    resource: routing_api.yml
    prefix:   /api

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


