gpi_auction_details:
    path:     /auction/details/{id}
    defaults: { _controller: GPIAuctionBundle:AuctionDetails:index }

gpi_auction_cancel:
    path:     /auction/cancel/{id}
    defaults: { _controller: GPIAuctionBundle:CancelAuction:index }

gpi_auction_add:
    path:     /auction/add
    defaults: { _controller: GPIAuctionBundle:PrepareAuction:index }

gpi_auction_add1:
    path:     /auction/add1/{commandId}
    defaults: { _controller: GPIAuctionBundle:PrepareSubcategoriesForAuction:index }

gpi_auction_add2:
    path:     /auction/add2/{commandId}
    defaults: { _controller: GPIAuctionBundle:AddAuction:index }

gpi_auction_finish:
    path:     /auction/finish/{auctionId}
    defaults: { _controller: GPIAuctionBundle:AddAuction:finish }

gpi_auction_edit:
    path:     /auction/edit/{id}
    defaults: { _controller: GPIAuctionBundle:AuctionEdit:edit }

gpi_auction_auctions_by_category:
    path:     /category/{categorySlug}
    defaults: { _controller: GPIAuctionBundle:AuctionsByCategory:index }

gpi_auction_list_ended:
    path:     /auctions_ended/
    defaults: { _controller: GPIAuctionBundle:ListProperlyEndedAuctions:show }

gpi_auction_list_not_active:
    path:     /auctions_not_active/
    defaults: { _controller: GPIAuctionBundle:ListNotActiveAuctions:show }
