services:
#    gpi_auction.example:
#        class: GPI\AuctionBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    gpi_auction.admin.auction:
        class: GPI\AuctionBundle\Admin\AuctionAdmin
        arguments: [~, GPI\AuctionBundle\Entity\Auction, GPIAuctionBundle:AuctionAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Lista aukcji}
    gpi_auction.admin.document:
        class: GPI\DocumentBundle\Admin\DocumentAdmin
        arguments: [~, GPI\DocumentBundle\Entity\Document, GPIDocumentBundle:DocumentAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Lista dokumentów}
    gpi_auction.auction_repository:
        class: GPI\AuctionBundle\Entity\AuctionRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - GPI\AuctionBundle\Entity\Auction
    gpi_sonata.category_repository:
        class: GPI\Sonata\ClassificationBundle\Entity\CategoryRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Application\Sonata\ClassificationBundle\Entity\Category
        calls:
            - [setAuctionRootCategoryId, [%gpi_auction.root_category_id%]]
    gpi.block.service.auction:
        id: gpi.block.service.auction
        class: GPI\Sonata\BlockBundle\Block\AuctionBlockService
        arguments:
            - gpi.block.service.auction
            - @templating
            - @gpi_auction.auction_repository
            - @doctrine.orm.entity_manager
            - @gpi_sonata.category_repository
        tags:
            - {name: sonata.block}
            - { name: knp_paginator.injectable, paginator: knp_paginator }
        calls:
            - [setRequest, [@request_stack]]
    gpi.block.service.categories:
        id: gpi.block.service.categories
        class: GPI\Sonata\BlockBundle\Block\CategoriesBlockService
        arguments:
            - gpi.block.service.categories
            - @templating
            - @gpi_sonata.category_repository
        tags:
            - {name: sonata.block}
        calls:
            - [setRequest, [@request_stack]]
    gpi_auction.form.auction:
        class: GPI\AuctionBundle\Form\AddAuctionType
        tags:
            - { name: form.type, alias: auction }
        arguments:
            - @gpi_sonata.category_repository
    gpi_auction.form.auction_update:
        class: GPI\AuctionBundle\Form\UpdateAuctionType
        tags:
            - { name: form.type, alias: auction_update }
        arguments:
            - @gpi_sonata.category_repository
    gpi_auction.form.document:
        class: GPI\AuctionBundle\Form\DocumentType
        tags:
            - { name: form.type, alias: document }
    gpi_auction.service.auction:
        class: GPI\CoreBundle\Model\Service\Auction
        arguments:
            - @gpi_core.model.calendar.calendar
            - %gpi_auction.allowedTimePeriods%
            - @gpi_auction.auction_repository
            - @security.token_storage
    gpi_core.model.calendar.calendar:
        class: GPI\CoreBundle\Model\Calendar\Calendar
    gpi_auction.entity.initializer:
        class: GPI\AuctionBundle\EventListener\AuctionEntityInitializer
        tags:
            - { name: doctrine.event_listener, event: postLoad }
        arguments:
            - @gpi_core.model.calendar.calendar