services:
    gpi_site.site_repository:
        class: GPI\SiteBundle\Entity\SiteRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - GPI\SiteBundle\Entity\Site
    gpi_site.admin.site:
        class: GPI\SiteBundle\Admin\SiteAdmin
        arguments: [~, GPI\SiteBundle\Entity\Site, GPISiteBundle:SiteAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Lista podstron}