gpi_offer_details:
    path:     /details/{id}
    defaults: { _controller: GPIOfferBundle:OfferDetails:index }

index:
    path:     /offer/add
    defaults: { _controller: GPIOfferBundle:AddOffer:index }
