gpi_offer_details:
    path:     /details/{id}
    defaults: { _controller: GPIOfferBundle:OfferDetails:index }

gpi_offer_add:
    path:     /offer/add
    defaults: { _controller: GPIOfferBundle:AddOffer:index }

gpi_offer_edit:
    path:     /offer/edit/{id}
    defaults: { _controller: GPIOfferBundle:OfferEdit:edit }

gpi_offer_offers_by_cetegory:
    path:     /category/{categorySlug}
    defaults: { _controller: GPIOfferBundle:OffersByCategory:index }
