gpi_offer_details:
    path:     /details/{id}
    defaults: { _controller: GPIOfferBundle:OfferDetails:index }

index:
    path:     /offer/add
    defaults: { _controller: GPIOfferBundle:AddOffer:index }

gpi_offer_offers_by_cetegories:
    path:     /category/{id}
