<?php

namespace GPI\AuctionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuctionRepository extends EntityRepository
{

    public function filterBy(AuctionFilterParams $params)
    {
        if ($params->getCategory() == null && $params->getName() == null) {
            $auctions = $this->findAll();
        } else {
            $queryBuilder = $this->createQueryBuilder('o');
            if ($params->getName() != null) {
                $name = $params->getName();
                $queryBuilder->andWhere('o.name LIKE :pac');
                $queryBuilder->setParameter('pac', '%' . $name . '%');
            }
            if ($params->getCategory() != null) {
                $category = $params->getCategory();
                $queryBuilder->andWhere('o.category = :cat');
                $queryBuilder->setParameter('cat', $category);
            }
            $auctions = $queryBuilder->getQuery()->getResult();
        }

        //        if ($name != null) {
        //            $queryBuilder = $this->createQueryBuilder('o')->where('o.name LIKE :pac');
        //            $queryBuilder->setParameter('pac', $name);
        //            $query = $queryBuilder->getQuery();
        //
        //            $auctions = $query->getResult();
        //        }else{
        //            $auctions = $this->findAll();
        //        }
        return $auctions;
    }
}
